name: base
channels:
  - bioconda
  - conda-forge
dependencies:
  - fastqc
  - fastqe
  - fastq-screen
  - picard
  - trimmomatic
  - bwa
  - samtools
  - vcftools
  - bcftools
  - gatk4
  - seqkit
  - mafft
  - raxml-ng
  # - sra-tools
  # - ffq
  # - nextflow
  # - nf-core
